# Generated by Django 6.1 on 2026-08-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_major_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='major',
            new_name='name',
        ),
    ]
