# Generated by Django 6.1 on 2026-08-19 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 12, 20)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 8, 28)),
            preserve_default=False,
        ),
    ]
