# Generated by Django 6.1 on 2026-08-20 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(editable=False, max_length=10)),
                ('professor', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('instruction_mode', models.CharField(choices=[('REGULAR', 'Regular'), ('ONLINE_MEETING', 'Online Meeting'), ('ONLINE_SYNCHRONIZE', 'Online Synchronize')], max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'subcode'), name='unique_course_subcode')],
            },
        ),
    ]
