# Generated by Django 6.1 on 2026-08-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
