# Generated by Django 6.1 on 2026-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_professorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorprofile',
            name='professor_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
